# Generated by Django 6.0.3 on 2026-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_category', models.CharField(choices=[('labor', 'Labor'), ('materials', 'Materials'), ('subcontractor', 'Subcontractor'), ('equipment', 'Equipment'), ('other', 'Other')], default='labor', max_length=30)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('materials', 'Materials'), ('subcontractor', 'Subcontractor'), ('equipment', 'Equipment'), ('other', 'Other')], default='labor', max_length=30)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('card_brand', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
